# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 18:35
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatter_type', models.CharField(max_length=100)),
                ('chatter_parent', models.CharField(max_length=500)),
                ('chatter_content', models.CharField(max_length=3000)),
                ('chatter_source', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EternalCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=500)),
                ('cost', models.IntegerField(default=0)),
                ('influence', models.CharField(max_length=200)),
                ('colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('rarity', models.CharField(max_length=100)),
                ('attack', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=200)),
                ('subtypes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('num', models.IntegerField(default=0)),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
            ],
        ),
        migrations.AddField(
            model_name='chatter',
            name='eternalcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.EternalCard'),
        ),
    ]
