# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 18:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatter',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
